# ----------- CONFIGURABLE START -----------
title:            "登龙（DLonng）"
description:      "选择大于努力"
url:              https://dlonng.com # Site url, without a slash at the end.
prompt:           "**本文原创首发于微信公号「登龙」，分享机器学习、算法编程、Python、机器人技术等原创文章，扫码即可关注**！"
signoff:          "DLonng" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-165904568-1 # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
name:             DLonng
links:
  - name:         Blog
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         Email
    url:          mailto:dlonnng@gmail.com
    external:     true
  - name:         GitHub
    url:          https://github.com/dlonng
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
